#ifndef HG_PARSING_HEADER_HPP
#define HG_PARSING_HEADER_HPP

#include <semparse/semparse.hpp>

extern semparse::semantic_graph_node DummyWhitespaceParent;
extern semparse::universal_address DummyDeepestAddress;
semparse::token_rules generate_token_rules();
bool parse_cpp_comment_begin(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_cpp_comment_character(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_cpp_comment_body(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_cpp_comment(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_begin(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_end(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_character(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_non_terminator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_body_element(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment_body(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_comment(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_space(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_newline(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_return(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_tab(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_whitespace_x(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
extern semparse::semantic_graph_node DummyWhitespaceTargetNode;
void whitespace_consume(semparse::parser& Parser, semparse::semantic_graph_node& TargetNode = DummyWhitespaceTargetNode, const bool Verbose = false);
bool parse_operator_plus(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_minus(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_multiply(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_divide(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_modulo(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_xor(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_and(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_or(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_complement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_not(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_less_than(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_greater_than(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_plus_plus(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_minus_minus(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_plus_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_minus_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_multiply_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_divide_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_modulo_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_xor_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_not_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_equal_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_less_than_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_greater_than_equal(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_logical_and(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_logical_or(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_dot(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_opening_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_closing_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_opening_square_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_closing_square_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_question_mark(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_colon(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_comma(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call_operator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_identifier(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_double_quote(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_string_constant_character(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_string_constant_escaped_character(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_string_constant_body_element(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_string_constant_body(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_string_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_statement_terminator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_name(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_declaration(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_bool(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_int8(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_uint8(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_int16(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_uint16(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_int32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_uint32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_int64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_uint64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_float32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_float64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_int8(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_uint8(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_int16(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_uint16(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_int32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_uint32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_int64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_uint64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_float32(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_literal_float64(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_string_prefix(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_wide_string_prefix(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_long_string_prefix(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_c_string_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_wide_string_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_long_string_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_array_begin(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_array_end(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_array(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_public_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_private_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_internal_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_extern_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_access_declaration(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_opening_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_closing_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_comma(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_parameter_name(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_parameter(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_parameter_list_elements(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_parameter_list(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_type_name_identifier(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_pointer_declaration(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_type_name(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_def_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_var_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_colon(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_variable_name(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_opening_square_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_closing_square_bracket(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_count(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_array_count(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_assignment_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_variable_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_uninitialized_variable_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_initialized_variable_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_octal_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_decimal_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_hexadecimal_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_float_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_double_constant(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_bracketed_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_subscript_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call_parameter_expression_element(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call_parameter_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call_parameters(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call_parameter_list(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_call(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_expression_element(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_expression_body(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_statement_block(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_initialization_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_condition_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_post_expression(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_header(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_for_loop(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_return_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_return_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_if_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_if_condition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_statement_block_or_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_else_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_else_block(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_if_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_typedef_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_type_alias(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_typedef_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_body(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_name_identifier(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_name_operator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_name(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_return_type_operator(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_return_type_declaration(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_declaration(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_opening_brace(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_closing_brace(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_infix(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_prefix(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_operator_type(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_function_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_import_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_import_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_header_keyword(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_header_statement(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_member(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_member_names_element(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_member_names(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_members_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_members(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_struct_definition(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);

class root_parser
{
public:
	root_parser();
	semparse::parse_results parse(const char* const Input, semparse::semantic_graph_node& TargetNode, const bool Verbose = false);
	semparse::parse_results parse(const semparse::string_type& Input, semparse::semantic_graph_node& TargetNode, const bool Verbose = false)
	{
		return parse(Input.c_str(), TargetNode, Verbose);
	}
	void address(const semparse::universal_address& NewAddress);
	semparse::universal_address address() const;
	semparse::parser& parser()
	{
		return Parser;
	}
	const semparse::parser& parser() const
	{
		return Parser;
	}
private:
	semparse::parser Parser;
	semparse::token_rules TokenRules;
};


//Anonymous elements
bool parse_anonymous_element_0(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_anonymous_element_1(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);
bool parse_anonymous_element_2(semparse::parser& Parser, semparse::semantic_graph_node& Result, semparse::semantic_graph_node& WhitespaceParent = DummyWhitespaceParent, semparse::universal_address& DeepestAddress = DummyDeepestAddress, const bool Verbose = false);

#endif
